# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['game.py'],
    pathex=[],
    binaries=[],
datas = [
    ('card_images/PNG/Cards (medium)/card_clubs_02.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_03.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_04.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_05.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_06.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_07.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_08.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_09.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_10.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_J.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_Q.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_K.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_clubs_A.png', 'card_images/PNG/Cards (medium)'),

    ('card_images/PNG/Cards (medium)/card_diamonds_02.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_03.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_04.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_05.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_06.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_07.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_08.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_09.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_10.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_J.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_Q.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_K.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_diamonds_A.png', 'card_images/PNG/Cards (medium)'),

    ('card_images/PNG/Cards (medium)/card_hearts_02.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_03.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_04.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_05.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_06.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_07.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_08.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_09.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_10.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_J.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_Q.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_K.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_hearts_A.png', 'card_images/PNG/Cards (medium)'),

    ('card_images/PNG/Cards (medium)/card_spades_02.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_03.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_04.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_05.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_06.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_07.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_08.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_09.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_10.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_J.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_Q.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_K.png', 'card_images/PNG/Cards (medium)'),
    ('card_images/PNG/Cards (medium)/card_spades_A.png', 'card_images/PNG/Cards (medium)'),

    ('board_game_icons/PNG/Default (64px)/skull.png', 'board_game_icons/PNG/Default (64px)'),
    ('board_game_icons/PNG/Default (64px)/shield.png', 'board_game_icons/PNG/Default (64px)'),

],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='game',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
